### ISSUE TITLE
关于 navy-apps/README.md 相关描述的疑问

### ISSUE THREAD

**Issue by lovelxc** [NJU-ProjectN/navy-apps#10]
在 [navy-apps/README.md](https://github.com/NJU-ProjectN/navy-apps/blob/master/README.md)中，有如下描述：
例如一个合法的 `/proc/dispinfo`文件例子如下:
```
WIDTH : 640
HEIGHT:480
```
这里的描述是否应该改为：
```
WIDTH: 640
HEIGHT: 480
```
> 其实就是空格位置有问题）

**Comment by sashimi-yzh** [comment]
原来的描述没问题, 和前文的说法对应的

**Comment by lovelxc** [comment]
但这和[native.cpp#L186](https://github.com/NJU-ProjectN/navy-apps/blob/master/libs/libos/src/native.cpp#L186)中的空格位置不一致，不知道这是否是个问题。。

**Comment by sashimi-yzh** [comment]
那是代码实现的考虑不全面

**Comment by lovelxc** [comment]
就是说native.cpp的部分是不对的，要按readme里的格式来吗？

**Comment by sashimi-yzh** [comment]
readme定义的是合法的输入, 你可以自行决定是否严格按它来实现.

**Comment by sashimi-yzh** [comment]
已在commit e8346911c80af39b63e47d8aba5878e43231ad63 中添加相关说明, 感谢指出这个问题!
