### ISSUE TITLE
非 PA 手册环境下的 libbdf 编译和 SDL 渲染问题

### ISSUE THREAD

**Issue by CookiePieWw** [NJU-ProjectN/navy-apps#11]
您好！我正在使用 Arch Linux 和 gcc-13 尝试编译运行 navy-apps 中的库和应用，遇到了一些问题。PA 中要求的环境是 Ubuntu 22.04，目前的 gcc 版本（大概是）gcc 11，因此这些问题可能是不同的发行版、 gcc 版本和 SDL2 版本带来的。

```bash
> uname -r
6.7.0-arch3-1
> gcc -v
gcc version 13.2.1 20230801 (GCC)
> sudo pacman -Q | grep sdl
sdl2 2.28.5-1
```

1. gcc 13 (只有 libstdc++) 禁止在 freestanding 环境下使用 malloc，因此 libbdf 的编译会失败

    ```
    // $NAVY_HOME/libs/libbdf
    > make ISA=native archive
    ...
    $NAVY_HOME/libs/libbdf/src/SDL_bdf.cpp:9:34: error: ‘malloc’ was not declared in this scope
    ...
    ```
    gcc 12 及以下不受影响。在根目录的 Makefile 里把 CXXFLAGS 中的 -ffreestanding 去掉之后才可以正常编译。gcc 13 的更新日志：
    > Additionally, libstdc++ now respects the -ffreestanding compiler option and so it is not necessary to build a separate freestanding installation of libstdc++.

2. native 下在其他线程（而不是主线程）使用 update_screen() 更新屏幕没有作用

    在 native 上运行 bird 或者 pal 时我发现窗口会一直黑屏，在 [native.cpp](https://github.com/NJU-ProjectN/navy-apps/blob/master/libs/libos/src/native.cpp) 中的 write 函数里加上 update_screen() 才能正常更新屏幕。按照[这个问题](https://discourse.libsdl.org/t/sdl-renderer-calls-from-different-thread-possible/25536)里的说法，可能是因为从其他线程中调用不一定会起到作用，取决于操作系统。

   >What’s even worse is that it can be platform-dependent. For example it seems that it’s normally OK to call SDL_SetWindowTitle() from another thread, but not (reliably) in MacOS. Similarly on most platforms it’s OK to call SDL_StartTextInput() and SDL_StopTextInput() from another thread, but not in iOS. And even SDL_ShowSimpleMessageBox(), which is supposed to be “callable at any time” in order to report an error, is thread specific on some platforms.

**Comment by zclorne** [comment]
同样遇到了第2个现象，根据[SDL_render.h](https://github.com/libsdl-org/SDL/blob/288aea3b40faf882f26411e6a3fe06329bba2c05/include/SDL_render.h#L1737)确实应该只在主线程上调用。
根据帖子中的说法，尝试将SDL_CreateWindowAndRenderer、SDL_SetWindowTitle、SDL_CreateTexture这些相关函数的调用移到与`update_screen()`的同一个线程中，也就是event_thread。在我的环境下可以正常更新屏幕了。

**Comment by Penghuige** [comment]
我正在使用Ubuntu24.04LTS, 这两个问题都遇上了Orz

**Comment by alexfanqi** [comment]
确实，sdl_render只能在主线程跑这问题我也碰到了，ubuntu上一直黑屏，fedora上压根窗口都显示不出来

**Comment by sashimi-yzh** [comment]
严格来说, 在原来的代码中, 调用`write`的线程也不一定是主线程, `event_thread`是由`SDL_CreateThread`创建的另一个线程.

我已经在commit b56b659255b8bd6f99e13cc484dc65d88f9f6a0f 中尝试将render相关的API更换为surface相关的API, 根据文档, 后者并未要求在主线程上调用, 有空的话还请各位帮忙测试一下能否修复问题. @alexfanqi @CookiePieWw @zclorne @Penghuige

**Comment by sashimi-yzh** [comment]
gcc 13的问题已在commit b80605c997a22ae9f06ddf96b1aec5adc0b2b949 中修复.

SDL渲染问题应该已解决, 若后续测试仍遇到相关问题, 可重新打开此issue继续讨论.
