### ISSUE TITLE
Makefile的clean规则需要完善

### ISSUE THREAD

**Issue by isnthzy** [NJU-ProjectN/navy-apps#12]
### Clean a single project (remove `build/`)
clean:
	rm -rf Makefile.html $(WORK_DIR)/build/ build/
navy-apps中讲义要求实现一部分库函数，这里的clean没有清除库函数编译出来的东西，这很危险

**Comment by sashimi-yzh** [comment]
用`make clean-all`来清除所有编译结果.

**Comment by isnthzy** [comment]
好吧，是我没仔细读readme了，我的锅
