### ISSUE TITLE
nslider的函数render()里存在问题

### ISSUE THREAD

**Issue by czlx-github** [NJU-ProjectN/navy-apps#14]
根据SDL1手册的描述：
`SDL_UpdateRect -- Makes sure the given area is updated on the given screen.`，
代码`SDL_UpdateRect(slide, 0, 0, 0, 0);` 不能在屏幕上显示图片（PA材料：“然后在miniSDL中实现SDL_UpdateRect(), 如果你的实现正确, 运行NSlider时将会显示第一张幻灯片.”）。
要显示图片需要更新到`screen`这个变量里。
但是这样做的话就需要先实现其它的SDL API，可对于这个测试用例的目的来说似乎不太妥当。
是否存在别的更好的办法？

**Comment by sashimi-yzh** [comment]
前文的讲义已经提到, 可以用NDL来实现SDL相关的API, 你可以尝试往这个方向思考一下.

**Comment by czlx-github** [comment]
自己实现的miniSDL，我的理解是调用`NDL_OpenCanvas()`和`NDL_DrawRect()`。
但把nslider的代码稍微修改后用Linux的SDL1跑这个程序，`SDL_UpdateRect()`不会把更新的结果显示在屏幕上，因为和参数`slide`关联的是BMP而不是实际显示的窗口(即`SDL_SetVideoMode()`的返回值)。
如果自己实现的`SDL_UpdateRect()`把结果显示到屏幕上，两者就冲突了，该参考哪个？
也可能是我的理解出了偏差，麻烦指正一下。

**Comment by sashimi-yzh** [comment]
我这边复现出你提到的问题了. 如果链接到Linux native的SDL库, 还需要实现`SDL_BlitSurface()`.

目前先按自己实现的`SDL_UpdateRect()`来处理吧, 今年秋季再修复这部分的代码和讲义.

**Comment by czlx-github** [comment]
好的，谢谢老师。

**Comment by sashimi-yzh** [comment]
代码已在commit fb9d4528184fef345f1d4123116140e2336006bf 中更新, 讲义已同步更新
